Add -a, reading a puzzle from a list of candidates in the 927 format.
dclamage/SudokuSolver pull request #22
Opened 2021-05-13 09:10 UTC by matjojo

The test works on the basis of symmetry, we create Boards, get their candidates string, and create a board from that.

2021-05-13 15:08 UTC, matjojo commented
After merging all tests still pass.

2021-05-13 17:13 UTC, dclamage requested changes
Thanks for the PR. Mostly looks good, just a couple small changes please.

The biggest one is that last night I did commit some modifications to `CreateFromGivens` which adds info the board about which givens were initially provided. I've added a review comment below for where that should appear.

Other than that, it's just minor style changes to match the rest of the codebase.

Thanks :)

2021-05-13 17:13 UTC, dclamage commented on SudokuSolver/SolverFactory.cs
> +
Last night I added some additional functionality to remember which givens were initially provided. Please see the code that uses `isOriginalGiven` in `CreateFromGivens` and add it here as well.

2021-05-13 17:13 UTC, dclamage commented on SudokuSolverConsole/Program.cs
>                  Console.WriteLine($"ERROR: Cannot provide more than one set of givens (f-puzzles URL, given string, blank grid).");
Add "candidates" to the list in parenthesis.

2021-05-13 17:13 UTC, dclamage commented on SudokuSolverConsole/Program.cs
> +                } else // if (haveCandidates)
[Style] Please make sure curly braces are always on their own line.

2021-05-14 11:46 UTC, matjojo commented on SudokuSolver/SolverFactory.cs
> +
Assuming that `isOriginalGiven` is only true for elements that have 1 and only 1 candidate I have this correctly implemented.

2021-05-14 17:24 UTC, dclamage approved these changes
Looks good, thanks!

2021-05-14 18:19 UTC, merged