Find the shortest contraction, with option to disable
dclamage/SudokuSolver pull request #53
Opened 2021-06-18 19:35 UTC by matjojo

The solver will now try to find the shortest contradiction instead of taking the first available.

This leads to more "logical" logical solves, and may, but not always, leads to shorter solves.

This will take a little more time, especially so on larger grids. So there is a new command-line option `-e` in place to disable this.

2021-06-18 19:37 UTC, matjojo commented on SudokuSolver/Solver.cs
> +                    return LogicResult.Changed;
Not a massive fan of this copied code, but I couldn't really think of a style compliant way to extract this out.

2021-06-19 13:31 UTC, matjojo commented on SudokuSolver/Solver.cs
> +                Tuple<int, Solver, int, int, int, StringBuilder> bestContradiction = null; // countChanges, solver, x, y, value, formattedContradictionReason
Just thinking about this more, if we want to take even more time to find (possibly) even shorter contradictions we may even want to move this to outside the allowedValueCount loop. I do fear that this may take a lot more time though. 

Maybe something to do if we can get a solid timing test set up with comparisons between commits. Not sure how we'd do that, but would be useful. We may be able to check out how GHC does this. I know for sure that they have a system to test that.

2021-06-19 21:27 UTC, dclamage requested changes
Just a few style changes needed, plus an error where you swapped `WIDTH` and `HEIGHT`, which doesn't break anything at the moment, but if I ever support non-square boards it'll cause issues.

Generally I like this idea, and this is certainly better than what I had before so I'm happy to approve it as-is with the small requested changes.

I think there's definitely a balance between finding the shortest contradictions and finding contradictions that are the most useful, which is why I look at bivalue cells first, then trivalue, etc. If performance is in question, it's possible that this process can be parallelized across cores (as long as the multithread option is used).

An alternative idea rather than finding the contradiction which visited the fewest cells would be to evaluate the results of the contradictions based on merit. Basically, make another copy of the board and evaluate the result of removing the contradiction candidate, limiting to only basic logic (singles and tuples only, for example). Using the contradiction that results in the best result afterward could be a better metric when compared to a contradiction that is simple to do but doesn't help as much. If two contradictions are tied based on merit, then the shortest contradiction of those choices could be used. What do you think?

2021-06-19 21:27 UTC, dclamage commented on SudokuSolver/Solver.cs
> +                Tuple<int, Solver, int, int, int, StringBuilder> bestContradiction = null; // countChanges, solver, x, y, value, formattedContradictionReason
Can you make this a struct instead of a Tuple? This is a rather large tuple and it's unclear what type represents.

2021-06-19 21:27 UTC, dclamage commented on SudokuSolver/Solver.cs
> +        private int amountCellsFilled()
`AmountCellsFilled()` All function names start with a capital letter please.

2021-06-19 21:27 UTC, dclamage commented on SudokuSolver/Solver.cs
> +            for (int x = 0; x < WIDTH; x++)
Use `i` and `j` when referencing cells, and also the outer loop is `HEIGHT` and inner loop is `WIDTH`. (Since the first coordinate is the row, and second coordinate is the column).

2021-06-20 02:03 UTC, merged